language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
  - secure: e9CXC2eFqtqxTDfuL7hN2thQO89i72NIIJ/J1q7dKWoUQdxRNt3wo2lmuiHDlAiFE9TLcHatrx7DVTqRQveyKHZcKCNfQcZUElT+Jo97bkW056MoaD7wKM/T6geKQ2ftqfhzHQHcgf8IF4GAFMuPG1zc0f/MFtHK5+d491cyj0Q=
  - secure: Fw5vkfplxUO5cY9zPt2be9I0xmz7G3peruLWVus5JpB5CL+N72yGzb8d+515hK77yqVJpELQfQorpxHvVVJtYLWXvCCynqv8SV2f9GW56MLX0io7XqbrNhytpTUH/bXXQnTuhxnx/RIZ5dRG7NHUXHAlI8xfLMlMo/+TKMWVjkU=
  - secure: hkX5ITaN1gptibJ3aJF+LmyryjDDuvaecq3wb3nQ/4yxv9QMwcnSyYC/TStTlaUbwViaHtUgazmJugnj2ODljVN+hlJJyBJJFpyqpzd1xQX+nPUKEefoyO7UB6MC7T+vSM7utqe18GcvMsvIw1tdwhk84PYr+qm9XhddkUsnmCc=

before_script:
  - composer self-update && composer --version
  - composer install --prefer-source --no-interaction
  - npm install -g bower
  - bower install
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - find -Lx . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

after_success:
  - sh -c "rsync -aruvz --delete --exclude='*.md' --exclude='.git*'--exclude='phpunit.xml*' --exclude='composer.*' --exclude='tests' --exclude='reports' ./* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}"