language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - secure: JGlE+/rooAZ11StpoyzP0kbNyOck08REekCAFp29rltTBi+ZJvzLWFfiJlgkcZ/aq/Ughmj169SeR1bgKpeuuYblIHadIHF2ferV9DdptvB8eqqNOPEmxSM+4sDqmrjHyw2rcnSaNVLuaMAnU5G9O1eazwO0EZC7Um3CZJ+7qLI=
    - secure: FpamtV/eWAmgfU3jnYytHnN/me0RivR4rDGVOIjkD/xhifidthg3w27PE+a6Jg3xi5SaIxGo7I79lehNpnOZ614fqhHLDYnVFaKlz7vG68XRTr7MRJ0x63XT3nHVxNmy0su+ocBL7D/Iwn/DNI8MpOed5fmpxBqPYA4nJ49itH0=

before_install:
  - openssl aes-256-cbc -K $encrypted_1891cd6c5b1c_key -iv $encrypted_1891cd6c5b1c_iv
    -in falcor.enc -out falcor -d
before_script:
  - composer self-update && composer --version
  - composer install --prefer-source --no-interaction
  - npm install -g bower
  - bower install
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - find -L . -name '*.php' -depth 1 -print0 | xargs -0 -n 1 -P 4 php -l

after_success:
  - chmod 600 $falcor
  - ssh-add $falcor
  - git remote add deploy $DEPLOY_URL
  - git add --all && git commit -m "Deployment triggered by commit ${TRAVIS_COMMIT}"
  - git config push.default simple
  - git config user.email travis@localhost.localdomain
  - git config user.name "Travis CI"
  - git push deploy master > /dev/null

